env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  project: './tsconfig.json'
  ecmaVersion: 2021
root: true
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - 'out'
